version: '2'
services:
    web:
        container_name: p_c_web
        build:
            context: ./
            dockerfile: web.docker
        volumes:
            - ./product_crud:/var/www/product_crud
        ports:
            - "8080:80"
        links:
            - app
        tty: true

    app:
        container_name: p_c_app
        build:
            context: ./
            dockerfile: app.docker
        volumes:
            - ./product_crud:/var/www/product_crud
        links:
            - mysql
            - redis
        tty: true

    mysql:
        container_name: p_c_mysql
        image: mysql:latest
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        ports:
            - "3306:3306"
        tty: true

    redis:
        container_name: p_c_redis
        image: redis:latest
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"
        command: redis-server --appendonly yes
        tty: true

volumes:
    mysql-data:
    redis-data:
        driver: local